name: ${PROJECT}

services:
  mqtt-broker:
    image: "am2h/mqtt:2.1"
    env_file: .env
    restart: unless-stopped
    ports:
      - "1883:1883"
      #- "1884:1884"
      - "9001:9001"
    volumes:
     - mqtt_data:/mosquitto/data
     - mqtt_log:/mosquitto/log
     - mqtt_user:/mosquitto/user
    networks:
      net:

volumes:
  mqtt_data:
  mqtt_log:
  mqtt_user:

networks:
  net:
    name: cloudflare-net
    external: true
